# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bafdd4183db0eadd9a0ca5afef33698554d87fa3c9e6c20e65a908cfa12cfd047c546daf5c174c1550c4edcd129f0eade52e40354af48ed64f23abc8df0ff64

test:
  secret_key_base: 62d3d57113ac069140df7b5f5d9184a63e9c82af7984f838a2dc14cc45df093a10ff0695478b9031695e6e606e9cb41c0cedcfd5ab4873ce5c18c44c23d1c9c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
